# Generated by Django 2.2.3 on 2020-01-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
